on:
  push:
    branches:
      - main

jobs:
  pulumi-dev:
    name: Pulumi Dev
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.18.3
      - run: npm install
        working-directory: pulumi
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: dev
          work-dir: pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  pulumi-prod:
    name: Pulumi Prod
    runs-on: ubuntu-20.04
    needs: [pulumi-dev]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.18.3
      - run: npm install
        working-directory: pulumi
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: dev
          work-dir: pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
