name: CD

on:
  push:
    branches:
      - main

jobs:
  pulumi-dev:
    uses: ./.github/workflows/pulumi.yml
    with:
      stack: dev
    secrets:
      access_token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  pulumi-prd:
    needs: [pulumi-dev]
    uses: ./.github/workflows/pulumi.yml
    with:
      stack: prod
    secrets:
      access_token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
