name: CD

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: ${{ matrix.command }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        command: ['build', 'lint', 'prettier:check', 'test']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.18.3
      - name: Install
        run: npm i -g npm@8 && npm ci
      - name: Run ${{ matrix.command }}
        run: npm run ${{ matrix.command }}
