name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  optimize-images:
    name: Optimize images
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
  pulumi:
    name: Pulumi
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.18.3
      - run: npm install
        working-directory: pulumi
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          work-dir: pulumi
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  ci:
    name: ${{ matrix.command }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        command: ['build', 'lint', 'prettier:check', 'test']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.18.3
      - run: npm i -g npm@8 && npm ci
      - run: npm run ${{ matrix.command }}
  acceptance:
    runs-on: ubuntu-20.04
    container: cypress/browsers@sha256:bbb87d21ebbe8ea8b784e06de66331f5c3b2bb3d5edb6dcf8af2320f19242c98
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.18.3
      - run: npm i -g npm@8 && npm ci
      - run: npm run cy:run:ci
