name: Cypress

on:
  schedule:
    - cron: '* * * * *'

jobs:
  cypress:
    name: Cypress
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-${{ matrix.version }}
    strategy:
      fail-fast: false
      matrix:
        version: ['chrome88-ff89', 'chrome91-ff89']
        browser: ['firefox', 'chrome']
        baseUrl: ['dev.lukeandjadi.com', 'lukeandjadi.com']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: ${{ matrix.browser }}
          start: yarn cy:run --record --key ${{ secrets.CYPRESS_KEY }} --config baseUrl="https://${{ matrix.baseUrl }}"
          spec: cypress/integration/*
          record: true
          parallel: true
