name: Cypress

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  cypress:
    name: Cypress
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-${{ matrix.version }}
    strategy:
      fail-fast: false
      matrix:
        version: ['chrome88-ff89', 'chrome91-ff89']
        browser: ['chrome']
        baseUrl: ['dev.lukeandjadi.com', 'lukeandjadi.com']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_KEY }}
        with:
          browser: ${{ matrix.browser }}
          start: yarn cy:run
          spec: cypress/integration/*
          record: false
          args: --config baseUrl="https://${{ matrix.baseUrl }}"
